### ISSUE TITLE
message box not opening

### ISSUE THREAD

**Issue by kubasic** [Xjph/ObservatoryCore#176]
looks like the path to plugin manager is hardcoded
noticed in 1.0.2, still present in 1.0.3

************** Exception Text **************
System.IO.FileLoadException: Could not load file or assembly 'MessageBox.Avalonia, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e4248c6fd4a6837a'. General Exception (0x80131500)
File name: 'MessageBox.Avalonia, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e4248c6fd4a6837a'
 ---> System.IO.FileLoadException: Could not load file or assembly 'MessageBox.Avalonia, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e4248c6fd4a6837a'. General Exception (0x80131500)
File name: 'MessageBox.Avalonia, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e4248c6fd4a6837a'
 ---> System.Exception: Unable to load assembly MessageBox.Avalonia
   at Observatory.PluginManagement.PluginManager.<>c__DisplayClass33_0.<LoadPluginAssembly>b__0(AssemblyLoadContext context, AssemblyName name) in C:\Users\Xjph\Repos\ObservatoryCore\ObservatoryCore\PluginManagement\PluginManager.cs:line 409
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly.<InternalLoad>g____PInvoke|49_0(NativeAssemblyNameParts* __pAssemblyNameParts_native, ObjectHandleOnStack __requestingAssembly_native, StackCrawlMarkHandle __stackMark_native, Int32 __throwOnFileNotFound_native, ObjectHandleOnStack __assemblyLoadContext_native, ObjectHandleOnStack __retAssembly_native)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Observatory.PluginManagement.PluginManager.<>c__DisplayClass33_0.<LoadPluginAssembly>b__0(AssemblyLoadContext context, AssemblyName name) in C:\Users\Xjph\Repos\ObservatoryCore\ObservatoryCore\PluginManagement\PluginManager.cs:line 405
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Observatory.BioInsights.BioInsightsSettings.PerformShowLegend()
   at Observatory.UI.SettingsForm.<>c__DisplayClass10_0.<CreateSettingButton>b__0(Object sender, EventArgs e) in C:\Users\Xjph\Repos\ObservatoryCore\ObservatoryCore\UI\SettingsForm.cs:line 272
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by Xjph** [comment]
You're using an outdated plugin that is not fully compatible with your current version of Observatory.
