### ISSUE TITLE
App closing itself during play

### ISSUE THREAD

**Issue by virosh** [Xjph/ObservatoryCore#54]
I am having a strange issue of the Observatory Core closing itself during gameplay. It's the same with the older version and this starting happening few weeks ago when i decided to start playing again.
I play in VR and the only other tool i have open is EDDiscovery. EDD and Observatory are started by an AHK script automatically, but are not controlled by it in any way - e.g. the script does not close them once the ED Client has been closed.
Everything is working during startup, however once i start playing the Observatory Core closes itself at some point. I can confirm that as i just lift my HMD and can see that the app is not running anymore. If i start it again and continue playing - it closes itself after a few minutes again.

Is there a debug mode or a log which i can check to see what is the reason the app is closing itself?

**Comment by Xjph** [comment]
A crash event should be written to the windows event log. Event Viewer, Windows Logs, Application, I believe.

Does this also happen if you try to read all, or is it only while monitoring?

**Comment by virosh** [comment]
It does not happen when i press "Read All".
I found the two event entries today:
```
Application: ObservatoryCore.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: The cloud operation was not completed before the time-out period expired. : 'C:\Users\<username>\Saved Games\Frontier Developments\Elite Dangerous\Journal.220203184135.01.log'
   at System.IO.FileStream.ReadNative(Span`1 buffer)
   at System.IO.FileStream.ReadSpan(Span`1 destination)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()
   at Observatory.LogMonitor.ReadAllLines(String path) in C:\Users\Xjph\Source\Repos\ObservatoryCore\ObservatoryCore\LogMonitor.cs:line 352
   at Observatory.LogMonitor.LogChangedEvent(Object source, FileSystemEventArgs eventArgs) in C:\Users\Xjph\Source\Repos\ObservatoryCore\ObservatoryCore\LogMonitor.cs:line 327
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state)
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__83_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```
```
Faulting application name: ObservatoryCore.exe, version: 0.1.353.51, time stamp: 0x619336bf
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, time stamp: 0xe01c7650
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0x292c
Faulting application start time: 0x01d8191c7ade2285
Faulting application path: C:\Users\<username>\AppData\Local\Programs\Elite Observatory\ObservatoryCore.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: fa412ef0-da83-441e-956d-7edcd801b2c2
Faulting package full name: 
Faulting package-relative application ID: 
```

I am usually Linux guy and use Windows to play games only. Debugging on Windows is somewhat obscure to me.
Hope this helps.

**Comment by Xjph** [comment]
Huh. Are you using OneDrive to sync your journal folder? Looks like a file sync is taking too long to finish and it's causing Observatory to timeout whole waiting to read the file. I might be able to increase the timeout, will look into it.

**Comment by virosh** [comment]
No OneDrive. I have a Nexcloud setup and yeah, i am syncing the journal logs in it.
The timeout is strange as the server is literally one hop away from me in the same network.
I will try to pause the sync client next time i play and will watch it again.

**Comment by Xjph** [comment]
I'll see what I can do to make journal reading more resiliant of longer operations. In the meantime yeah, as you said pausing syncing is hopefully a usable workaround.

**Comment by virosh** [comment]
Just to update you that pausing the sync did the magic trick. I did not have any crashes.

**Comment by virosh** [comment]
@Xjph, I haven't played for a while, but recently started again. Just to note that this issue is not existing anymore (at least with NextCloud).
I forgot to disable the sync before playing and the app was working fine, without issues and crashes.
After that I tested it a couple of times and now it works without disabling the sync of my NexCloud client.

**Comment by Xjph** [comment]
Closing this, re: most recent comment.
